extends Node

var systems : Dictionary

var polygon : PackedVector2Array = []
func _ready() -> void:
	DisplayServer.window_set_mode(DisplayServer.WINDOW_MODE_FULLSCREEN)
	var current_size = DisplayServer.window_get_size() 
	var v_button_bar_width = 60
	polygon = [Vector2(0,0),
				Vector2(v_button_bar_width,0),
				Vector2(v_button_bar_width,current_size.y),
				Vector2(0,current_size.y)]
	get_window().set_mouse_passthrough_polygon(polygon)

#1600, 900
var screen_size: Vector2 = Vector2(1600,900)
#-------------------------------
var bag_size: int = 10 # 12
var round_time_min : float = 38.0 # 45.0
var round_time_max : float = 132.0 # 148
#-------------------------------
var rom_dir: String = "Z:\\roms"
#--------- Standalones
var cemu: String = "D:\\Emulation\\storage\\cemu\\Cemu.exe"
var azahar: String = "D:\\Emulation\\storage\\azahar\\azahar.exe"
var dolphin: String = "D:\\Emulation\\storage\\dolphin\\Dolphin.exe"
var rpcs3_dir: String = "D:\\Emulation\\storage\\rpcs3\\rpcs3.exe"
var vita3k_dir: String = "D:\\Emulation\\storage\\Vita3k\\Vita3K.exe"
var xemu: String = "D:\\Emulation\\storage\\xemu\\xemu.exe"
var xenia: String = "D:\\Emulation\\storage\\xenia\\xenia_canary.exe"
var sudachi: String = "D:\\Emulation\\storage\\sudachi\\sudachi.exe"
#--------- RA
var retroarch: String = "C:\\Users\\carter\\Documents\\GitHub\\retroarch\\retroarch.exe"
var ra_cores_dir: String = "C:\\Users\\carter\\Documents\\GitHub\\retroarch\\cores"
#---------
var sys_default := {
	"3do": {"name": "3DO Interactive Multiplayer", 
		"emu": retroarch, 
		"core": "\\opera_libretro.dll", 
		"args": ["-L" , "{CORE}", "{PATH}"],
		"method": "udp",
		"default_state": true,
		"icon": preload("res://Sprites/ui_logos/3DO Interactive Multiplayer.png")},
	"3ds": {"name": "Nintendo 3DS", 
		#"emu": azahar, 
		"emu": retroarch, 
		"core": "\\citra_libretro.dll", 
		#"args": ["{PATH}"],
		"args": ["-L" , "{CORE}", "{PATH}"],
		"method": "udp",
		"default_state": true,
		"icon": preload("res://Sprites/ui_logos/Nintendo 3DS.png")},
	"arcade": {"name": "Arcade", 
		"emu": retroarch, 
		"core": "\\mame_libretro.dll", 
		"args": ["-L" , "{CORE}", "{PATH}"],
		"method": "udp",
		"default_state": true,
		"icon": preload("res://Sprites/ui_logos/MAME.png")},
	"atari2600": {"name": "Atari 2600", 
		"emu": retroarch, 
		"core": "\\stella_libretro.dll", 
		"args": ["-L" , "{CORE}", "{PATH}"],
		"method": "udp",
		"default_state": true,
		"icon": preload("res://Sprites/ui_logos/Atari 2600.png")},
	"atarilynx": {"name": "Atari Lynx", 
		"emu": retroarch, 
		"core": "\\handy_libretro.dll", 
		"args": ["-L" , "{CORE}", "{PATH}"],
		"method": "udp",
		"default_state": true,
		"icon": preload("res://Sprites/ui_logos/Atari Lynx.png")},
	#"atomiswave": {"name": "atomiswave", "emu": "", "core": "", "args": ""},
	"c64": {"name": "Commodore C64", 
		"emu": retroarch, 
		"core": "\\vice_x64_libretro.dll", 
		"args": ["-L" , "{CORE}", "{PATH}"],
		"method": "udp",
		"default_state": true,
		"icon": preload("res://Sprites/ui_logos/Commodore 64.png")},
	"dc": {"name": "Dreamcast", 
		"emu": retroarch, 
		"core": "\\flycast_libretro.dll", 
		"args": ["-L" , "{CORE}", "{PATH}"],
		"method": "udp",
		"default_state": true,
		"icon": preload("res://Sprites/ui_logos/Sega Dreamcast.png")},
	"dos": {"name": "DOS", 
		"emu": retroarch, 
		"core": "\\dosbox_pure_libretro.dll", 
		"args": ["-L" , "{CORE}", "{PATH}"],
		"method": "udp",
		"default_state": true,
		"icon": preload("res://Sprites/ui_logos/MS-DOS.png")},
	"fds": {"name": "Family Computer Disk System", 
		"emu": retroarch, 
		"core": "", 
		"args": ["-L" , "{CORE}", "{PATH}"],
		"method": "udp",
		"default_state": true,
		"icon": preload("res://Sprites/ui_logos/Nintendo Famicom Disk System.png")},
	"g-and-w": {"name": "Game & Watch", 
		"emu": retroarch, 
		"core": "\\gw_libretro.dll", 
		"args": ["-L" , "{CORE}", "{PATH}"],
		"method": "udp",
		"default_state": true,
		"icon": preload("res://Sprites/ui_logos/Nintendo Game & Watch.png")},
	"gamegear": {"name": "Game Gear", 
		"emu": retroarch, 
		"core": "\\genesis_plus_gx_libretro.dll", 
		"args": ["-L" , "{CORE}", "{PATH}"],
		"method": "udp",
		"default_state": true,
		"icon": preload("res://Sprites/ui_logos/Sega Game Gear.png")},
	"gb": {"name": "Game Boy", 
		"emu": retroarch, 
		"core": "\\gambatte_libretro.dll", 
		"args": ["-L" , "{CORE}", "{PATH}"],
		"method": "udp",
		"default_state": true,
		"icon": preload("res://Sprites/ui_logos/Nintendo Game Boy.png")},
	"gba": {"name": "Game Boy Advance", 
		"emu": retroarch, 
		"core": "\\mgba_libretro.dll", 
		"args": ["-L" , "{CORE}", "{PATH}"],
		"method": "udp",
		"default_state": true,
		"icon": preload("res://Sprites/ui_logos/Nintendo Game Boy Advance.png")},
	"gbc": {"name": "Game Boy Color", 
		"emu": retroarch, 
		"core": "\\gambatte_libretro.dll", 
		"args": ["-L" , "{CORE}", "{PATH}"],
		"method": "udp",
		"default_state": true,
		"icon": preload("res://Sprites/ui_logos/Nintendo Game Boy Color.png")},
	"genesis-slash-megadrive": {"name": "Genesis", 
		"emu": retroarch, 
		"core": "\\genesis_plus_gx_libretro.dll", 
		"args": ["-L" , "{CORE}", "{PATH}"],
		"method": "udp",
		"default_state": true,
		"icon": preload("res://Sprites/ui_logos/Sega Genesis.png")},
	#"model2": {"name": "model2", "emu": "", "core": "", "args": ""},
	#"model3": {"name": "model3", "emu": "", "core": "", "args": ""},
	"msx": {"name": "MSX", 
		"emu": retroarch, 
		"core": "\\fmsx_libretro.dll", 
		"args": ["-L" , "{CORE}", "{PATH}"],
		"method": "udp",
		"default_state": true,
		"icon": preload("res://Sprites/ui_logos/Microsoft MSX.png")},
	"n64": {"name": "Nintendo 64", 
		"emu": retroarch, 
		"core": "\\mupen64plus_next_libretro.dll", 
		"args": ["-L" , "{CORE}", "{PATH}"],
		"method": "udp",
		"default_state": true,
		"icon": preload("res://Sprites/ui_logos/Nintendo 64.png")},
	#"naomi": {"name": "naomi", "emu": "", "core": "", "args": ""},
	#"naomi2": {"name": "naomi2", "emu": "", "core": "", "args": ""},
	"nds": {"name": "Nintendo DS", 
		"emu": retroarch, 
		"core": "\\melondsds_libretro.dll", 
		"args": ["-L" , "{CORE}", "{PATH}"],
		"method": "udp",
		"default_state": true,
		"icon": preload("res://Sprites/ui_logos/Nintendo DS.png")},
	"neo-geo-pocket-color": {"name": "Neo Geo Pocket Color", 
		"emu": retroarch, 
		"core": "\\mednafen_ngp_libretro.dll", 
		"args": ["-L" , "{CORE}", "{PATH}"],
		"method": "udp",
		"default_state": true,
		"icon": preload("res://Sprites/ui_logos/SNK Neo Geo Pocket Color.png")},
	#"neogeoaes": {"name": "neogeoaes", "emu": "", "core": "", "args": ""},
	"nes": {"name": "Nintendo Entertainment System", 
		"emu": retroarch, 
		"core": "\\mesen_libretro.dll", 
		"args": ["-L" , "{CORE}", "{PATH}"],
		"method": "udp",
		"default_state": true,
		"icon": preload("res://Sprites/ui_logos/Nintendo Entertainment System.png")},
	"ngc": {"name": "Nintendo GameCube", 
		"emu": retroarch, 
		"core": "\\dolphin_libretro.dll", 
		#"args": ["-e" , "{PATH}", "--batch" ,"--config" , "Dolphin.Display.Fullscreen=True"],
		"args": ["-L" , "{CORE}", "{PATH}"],
		"method": "udp",
		"default_state": true,
		"icon": preload("res://Sprites/ui_logos/Nintendo GameCube.png")},
	#"pico8": {"name": "pico8", "emu": "", "core": "", "args": ""},
	"ps": {"name": "PlayStation", 
		"emu": retroarch, 
		"core": "\\swanstation_libretro.dll", 
		"args": ["-L" , "{CORE}", "{PATH}"],
		"method": "udp",
		"default_state": true,
		"icon": preload("res://Sprites/ui_logos/Sony Playstation.png")},
	"ps2": {"name": "PlayStation 2", 
		"emu": retroarch, 
		"core": "\\pcsx2_libretro.dll", 
		"args": ["-L" , "{CORE}", "{PATH}"],
		#"args": ["-fullscreen" , "{PATH}"],
		"method": "udp",
		"default_state": true,
		"icon": preload("res://Sprites/ui_logos/Sony Playstation 2.png")},
	"ps3": {"name": "PlayStation 3", 
		"emu": null, 
		"core": "", 
		"args": "",
		"method": "udp",
		"default_state": false,
		"icon": preload("res://Sprites/ui_logos/Sony Playstation 3.png")},
	"ps4--1": {"name": "PlayStation 4", 
		"emu": null, 
		"core": "", 
		"args": "",
		"method": "udp",
		"default_state": false,
		"icon": preload("res://Sprites/ui_logos/Sony Playstation 4.png")},
	"psp": {"name": "PlayStation Portable", 
		"emu": retroarch, 
		"core": "\\ppsspp_libretro.dll", 
		"args": ["-L" , "{CORE}", "{PATH}"],
		"method": "udp",
		"default_state": true,
		"icon": preload("res://Sprites/ui_logos/Sony PSP.png")},
	"psvita": {"name": "PlayStation Vita", 
		"emu": null, 
		"core": "", 
		"args": "",
		"method": "udp",
		"default_state": false,
		"icon": preload("res://Sprites/ui_logos/Sony PS Vita.png")},
	"saturn": {"name": "SEGA Saturn", 
		"emu": retroarch, 
		"core": "\\mednafen_saturn_libretro.dll", 
		"args": ["-L" , "{CORE}", "{PATH}"],
		"method": "udp",
		"default_state": true,
		"icon": preload("res://Sprites/ui_logos/Sega Saturn (Japan).png")},
	"sega32": {"name": "Sega 32X", 
		"emu": retroarch, 
		"core": "\\picodrive_libretro.dll", 
		"args": ["-L" , "{CORE}", "{PATH}"],
		"method": "udp",
		"default_state": true,
		"icon": preload("res://Sprites/ui_logos/Sega 32X.png")},
	"segacd": {"name": "Sega CD", 
		"emu": retroarch, 
		"core": "\\genesis_plus_gx_libretro.dll", 
		"args": ["-L" , "{CORE}", "{PATH}"],
		"method": "udp",
		"default_state": true,
		"icon": preload("res://Sprites/ui_logos/Sega CD.png")},
	"sg1000": {"name": "SG-1000", 
		"emu": retroarch, 
		"core": "\\genesis_plus_gx_libretro.dll", 
		"args": ["-L" , "{CORE}", "{PATH}"],
		"method": "udp",
		"default_state": true,
		"icon": preload("res://Sprites/ui_logos/Sega SG-1000.png")},
	"sms": {"name": "Sega Master System", 
		"emu": retroarch, 
		"core": "\\genesis_plus_gx_libretro.dll", 
		"args": ["-L" , "{CORE}", "{PATH}"],
		"method": "udp",
		"default_state": true,
		"icon": preload("res://Sprites/ui_logos/Sega Master System.png")},
	"snes": {"name": "Super Nintendo Entertainment System", 
		"emu": retroarch, 
		"core": "\\snes9x_libretro.dll", 
		"args": ["-L" , "{CORE}", "{PATH}"],
		"method": "udp",
		"default_state": true,
		"icon": preload("res://Sprites/ui_logos/Super Nintendo Entertainment System.png")},
	"switch": {"name": "Nintendo Switch", #Doesnt like WinHide, cant be brought to front.
		"emu": sudachi, 
		"core": null, 
		"args": ["-g","{PATH}","-f"],
		"method": "suspend",
		"default_state": false,
		"icon": preload("res://Sprites/ui_logos/Nintendo Switch.png")},
	"turbografx-16-slash-pc-engine-cd": {"name": "TurboGrafx CD", 
		"emu": retroarch, 
		"core": "\\mednafen_pce_libretro.dll", 
		"args": ["-L" , "{CORE}", "{PATH}"],
		"method": "udp",
		"default_state": true,
		"icon": preload("res://Sprites/ui_logos/NEC TurboGrafx-CD.png")},
	"turbografx16--1": {"name": "TurboGrafx-16", 
		"emu": retroarch, 
		"core": "\\mednafen_pce_libretro.dll", 
		"args": ["-L" , "{CORE}", "{PATH}"],
		"method": "udp",
		"default_state": true,
		"icon": preload("res://Sprites/ui_logos/NEC TurboGrafx-16.png")},
	"virtualboy": {"name": "Virtual Boy", 
		"emu": retroarch, 
		"core": "\\mednafen_vb_libretro.dll", 
		"args": ["-L" , "{CORE}", "{PATH}"],
		"method": "udp",
		"default_state": true,
		"icon": preload("res://Sprites/ui_logos/Nintendo Virtual Boy.png")},
	"wii": {"name": "Wii", #Can't run two WII Dolphin instances, as they conflict sharing a nand.
		"emu": retroarch, 
		"core": "\\dolphin_libretro.dll", 
		#"args": ["-e" , "{PATH}", "--batch" ,"--config" , "Dolphin.Display.Fullscreen=True"],
		"args": ["-L" , "{CORE}", "{PATH}"],
		"method": "udp",
		"default_state": true,
		"icon": preload("res://Sprites/ui_logos/Nintendo Wii.png")},
	"wiiu": {"name": "Wii U", #Doesnt WinHide right?
		"emu": cemu, 
		"core": null, 
		"args": ["-g" , "{PATH}", "-f"],
		"method": "suspend",
		"default_state": false,
		"icon": preload("res://Sprites/ui_logos/Nintendo Wii U.png")},
	"win3x": {"name": "Windows 3.x", 
		"emu": retroarch, 
		"core": "\\dosbox_pure_libretro.dll", 
		"args": ["-L" , "{CORE}", "{PATH}"],
		"method": "udp",
		"default_state": true,
		"icon": preload("res://Sprites/ui_logos/Windows 3.x.png")},
	"xbox": {"name": "Xbox", #Thinks it's directory is Godot's dir, breaking links.
		"emu": xemu, 
		"core": null, 
		"args": ["{PATH}"],
		"method": "suspend",
		"default_state": false,
		"icon": preload("res://Sprites/ui_logos/Microsoft Xbox.png")},
	"xbox360": {"name": "Xbox 360", 
		"emu": xenia, 
		"core": null, 
		"args": ["--fullscreen=true", "{PATH}"],
		"method": "suspend",
		"default_state": true,
		"icon": preload("res://Sprites/ui_logos/Microsoft Xbox 360.png")},
}
